site_name: My Personal Site
theme:
  name: material
  logo: images/logo.png  # Path to your logo image
  palette:
    primary: 'blue'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - navigation.tabs
    - naviagion.instant
    - navigation.top
    - search.suggest
  favicon: images/logo.png

nav:
  - Home: index.md
  - About: about.md
  - Projects:
      - Java Memory Game: projects/Java_Memory_Game.md
      - Android Weather XML: projects/Android_Weather_XML.md
      - Android Weather Compose: projects/Android_Weather_Compose.md
extra_css:
  - 'stylesheets/custom.css'
extra_javascript:
  - 'javascripts/custom.js'
plugins:
  - search


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences